# Generated by Django 3.2.9 on 2021-12-22 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customize',
            fields=[
                ('customizeid', models.AutoField(primary_key=True, serialize=False, verbose_name='CUSTOMIZEID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('template', models.CharField(blank=True, default='', max_length=255)),
                ('pcolour', models.CharField(blank=True, default='', max_length=255)),
                ('scolour', models.CharField(blank=True, default='', max_length=255)),
                ('fonts', models.CharField(blank=True, default='', max_length=255)),
                ('lastedited', models.CharField(blank=True, default=django.utils.timezone.now, max_length=255)),
                ('selected', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
