# Generated by Django 4.0.4 on 2022-09-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendorid', models.AutoField(primary_key=True, serialize=False, verbose_name='CUSTID')),
                ('title', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('gsttype', models.CharField(max_length=100, null=True)),
                ('gstin', models.CharField(default='', max_length=100)),
                ('panno', models.CharField(max_length=100, null=True)),
                ('sourceofsupply', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=100, null=True)),
                ('openingbalance', models.CharField(max_length=100, null=True)),
                ('paymentterms', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('shipstreet', models.CharField(max_length=100, null=True)),
                ('shipcity', models.CharField(max_length=100, null=True)),
                ('shipstate', models.CharField(max_length=100, null=True)),
                ('shippincode', models.CharField(max_length=100, null=True)),
                ('shipcountry', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
