# Generated by Django 4.0.4 on 2022-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_company_vendor_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendorid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='VENID'),
        ),
    ]
