# Generated by Django 4.0.4 on 2022-09-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_vendor_vendorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='cid',
        ),
    ]
