# Generated by Django 4.0.4 on 2022-09-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_vendor_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseorder',
            fields=[
                ('porderid', models.AutoField(primary_key=True, serialize=False, verbose_name='pid')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_details', models.TextField()),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('gsttype', models.CharField(max_length=100, null=True)),
                ('gstin', models.CharField(default='', max_length=100)),
                ('panno', models.CharField(max_length=100, null=True)),
                ('placeofsupply', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=100, null=True)),
                ('openingbalance', models.CharField(max_length=100, null=True)),
                ('paymentterms', models.CharField(max_length=100, null=True)),
                ('puchaseorder_no', models.IntegerField(default=1000)),
                ('sourceofsupply', models.CharField(max_length=100, null=True)),
                ('destiofsupply', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('contact_address', models.CharField(max_length=255, null=True)),
                ('contact_person', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('deliver_date', models.DateField(null=True)),
                ('credit_period', models.CharField(max_length=100, null=True)),
                ('due_date', models.CharField(max_length=100, null=True)),
                ('sub_total', models.CharField(max_length=100, null=True)),
                ('sgst', models.CharField(max_length=100, null=True)),
                ('cgst', models.CharField(max_length=100, null=True)),
                ('igst', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('tcs', models.CharField(max_length=100, null=True)),
                ('round_off', models.CharField(max_length=100, null=True)),
                ('tax_amount', models.CharField(max_length=100, null=True)),
                ('grand_total', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='porder_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchaseorder')),
            ],
        ),
    ]
