# Generated by Django 4.0.4 on 2022-09-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_purchaseorder_porder_item_itemtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='net_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Billed', 'Billed')], default='Draft', max_length=150),
        ),
    ]
