# Generated by Django 4.0.4 on 2022-09-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_purchaseorder_company_name_purchaseorder_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='net_amount',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
