# Generated by Django 4.0.4 on 2022-09-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_purchaseorder_net_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tcs_amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
