# Generated by Django 4.0.4 on 2022-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_purchaseorder_tcs_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(default=None, upload_to='purchaseorder'),
        ),
    ]
