# Generated by Django 4.0.4 on 2022-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_purchaseorder_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemtable',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False, verbose_name='ITMID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('tax_reference', models.CharField(max_length=100)),
                ('purchase_cost', models.CharField(max_length=100)),
                ('sales_cost', models.CharField(max_length=100)),
                ('tax_rate', models.CharField(max_length=100)),
                ('acount_pur', models.CharField(max_length=100)),
                ('account_sal', models.CharField(max_length=100)),
                ('pur_desc', models.CharField(max_length=100)),
                ('sale_desc', models.CharField(max_length=100)),
                ('intra_st', models.CharField(max_length=100)),
                ('inter_st', models.CharField(max_length=100)),
                ('inventry', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
