# Generated by Django 4.0.4 on 2022-09-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_itemtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtable',
            old_name='name',
            new_name='item_name',
        ),
    ]
