# Generated by Django 4.0.4 on 2022-09-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_name_itemtable_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtable',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='gsttype',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='openingbalance',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='panno',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='paymentterms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='placeofsupply',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor_details',
        ),
    ]
