# Generated by Django 4.0.4 on 2022-09-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_purchasebill_bill_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_item',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill'),
        ),
    ]
