# Generated by Django 4.0.4 on 2022-10-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_bill_item_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed')], default='Draft', max_length=150),
        ),
    ]
