# Generated by Django 4.0.4 on 2022-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_expenses_alter_purchasebill_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expenses',
            new_name='purchase_expense',
        ),
    ]
