# Generated by Django 4.0.4 on 2022-10-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rename_expenses_purchase_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditperiod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newperiod', models.IntegerField()),
            ],
        ),
    ]
