# Generated by Django 4.0.4 on 2022-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_creditperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='balance_due',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
