# Generated by Django 4.0.4 on 2022-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_purchasebill_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
