# Generated by Django 4.0.4 on 2022-10-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_purchasebill_amtrecvd'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasepayment',
            fields=[
                ('pymntid', models.AutoField(primary_key=True, serialize=False, verbose_name='pyid')),
                ('reference', models.IntegerField(default=1000)),
                ('vendor', models.CharField(max_length=100)),
                ('paymentdate', models.DateField(null=True)),
                ('paymentmethod', models.CharField(max_length=100, null=True)),
                ('depositeto', models.CharField(max_length=100)),
                ('paymentamount', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchasepayment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdate', models.DateField(null=True)),
                ('billno', models.CharField(max_length=100, null=True)),
                ('billamount', models.CharField(max_length=100, null=True)),
                ('amountdue', models.CharField(max_length=100, null=True)),
                ('payments', models.CharField(max_length=100, null=True)),
                ('pymnt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasepayment')),
            ],
        ),
    ]
