# Generated by Django 4.0.4 on 2022-10-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_purchasepayment_purchasepayment1'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
