# Generated by Django 4.0.4 on 2022-10-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_purchasebill_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newmethod', models.CharField(max_length=100)),
            ],
        ),
    ]
