# Generated by Django 4.0.4 on 2022-10-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_statment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('transactions', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('details2', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default='', null=True)),
                ('payments', models.FloatField(default='', null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('paymnt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasepayment')),
                ('pbill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
            ],
        ),
    ]
