# Generated by Django 4.0.4 on 2022-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_vendor_statment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_statment',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
